spring:
  application:
    name: ms-andesstay-audit
  profiles:
    default: azure
  config:
    import: optional:file:./.env
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://database-1.cri8jc4fzsag.us-east-1.rds.amazonaws.com:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgressql}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info

andesstay:
  azure:
    issuer-uri: ${AZURE_ISSUER_URI:https://login.microsoftonline.com/35442bb9-6147-4555-8ac7-7aea33ca4c73/v2.0}
    audience: ${AZURE_AUDIENCE:api://5bf59bf1-a4c7-4169-975d-8976a17e9b60}
  cors:
    allowed-origins: ${ANDESSTAY_CORS_ORIGINS:http://127.0.0.1:4200,http://localhost:4200,http://localhost:5173}

---
spring:
  config:
    activate:
      on-profile: azure
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_ISSUER_URI:https://login.microsoftonline.com/35442bb9-6147-4555-8ac7-7aea33ca4c73/v2.0}

---
spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_ISSUER_URI:http://localhost/unused}

andesstay:
  azure:
    issuer-uri: http://localhost/unused
    audience: local